export const users = [
  {
    name: "Gopi Admin",
    email: "admin@kovairealestate.com",
    password: "123456",
    phoneNumber: "9000000001",
    location: "Coimbatore",
    role: "admin",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/initials/svg?seed=Gopi%Admin",
      public_id: "default_admin",
    },
    socialMediaLinks: {
      facebook: null,
      youtube: null,
      instagram: null,
    },
  },
  {
    name: "Arun Kumar",
    email: "arun.agent@kovairealestate.com",
    password: "123456",
    phoneNumber: "9000000002",
    location: "Coimbatore",
    role: "seller",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/initials/svg?seed=Arun%20Kumar",
      public_id: "agent_1",
    },
    socialMediaLinks: {
      facebook: null,
      youtube: null,
      instagram: "https://instagram.com/arun.agent",
    },
  },
  {
    name: "Priya Sharma",
    email: "priya.agent@kovairealestate.com",
    password: "123456",
    phoneNumber: "9000000003",
    location: "Coimbatore",
    role: "seller",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/initials/svg?seed=Priya%20Sharma",
      public_id: "agent_2",
    },
    socialMediaLinks: {
      facebook: "https://facebook.com/priya.agent",
      youtube: null,
      instagram: null,
    },
  },
  {
    name: "Karthik Raj",
    email: "karthik.agent@kovairealestate.com",
    password: "123456",
    phoneNumber: "9000000004",
    location: "Coimbatore",
    role: "seller",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/initials/svg?seed=Karthik%20Raj",
      public_id: "agent_3",
    },
    socialMediaLinks: {
      facebook: null,
      youtube: null,
      instagram: null,
    },
  },
  {
    name: "Meena Lakshmi",
    email: "meena.agent@kovairealestate.com",
    password: "123456",
    phoneNumber: "9000000005",
    location: "Coimbatore",
    role: "seller",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/initials/svg?seed=Meena%20Lakshmi",
      public_id: "agent_4",
    },
    socialMediaLinks: {
      facebook: null,
      youtube: "https://youtube.com/@meenarealestate",
      instagram: null,
    },
  },
  {
    name: "Ravi Shankar",
    email: "ravi.agent@kovairealestate.com",
    password: "123456",
    phoneNumber: "9000000006",
    location: "Coimbatore",
    role: "seller",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/initials/svg?seed=Ravi%20Shankar",
      public_id: "agent_5",
    },
    socialMediaLinks: {
      facebook: null,
      youtube: null,
      instagram: "https://instagram.com/ravi.agent",
    },
  },
];
